# netlify.toml
[build]
  command = "DATABASE_URL=file:./dev.db npm run prisma:generate && npm run build"
  publish  = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"